### ISSUE TITLE
I think you know what is this...

### ISSUE THREAD

**Issue by K-Guan** [FiveYellowMice/de-menu#1]
# file name: PKGBUILD

```
pkgname='de-menu'
pkgver=1.0.0
pkgrel=1
pkgdesc="A desktop selection menu for startx users to avoid editing .xinitrc while switching desktops."
arch=('i686' 'x86_64')
url="https://github.com/FiveYellowMice/de-menu"
license=('GPL2')
depends=('xorg-xinit' 'xorg-server' 'bash')
source=("${pkgname}::git://github.com/FiveYellowMice/${pkgname}.git")
md5sums=('SKIP')

package() {
	cd "${srcdir}"/${pkgname}

	mkdir -p ${pkgdir}/usr/bin
	cp de-menu ${pkgdir}/usr/bin
}
```

**Comment by FiveYellowMice** [comment]
Since it is a git repo, it should not have a version number like '1.0.0', instead, the git version. And package name should be followed by '-git' to show this is from git. Those are the rules of the AUR. 
I think you should read Arch Wiki more carefully.
What's more, as said in README.md, user needs to manually edit their .xinitrc. This note should be showed when installing the package.

**Comment by K-Guan** [comment]
Hum, you're right. So what do you think about this?

**Comment by K-Guan** [comment]
Q: What do you mean about the 'git version'?

**Comment by FiveYellowMice** [comment]
Git version is something like this: 

![screenshot 2015-09-06 at 22 36 03](https://cloud.githubusercontent.com/assets/9077203/9704367/de93f466-54e7-11e5-822d-fb4d5777135f.png)

See the 'a4e8908ffe'? That's it.

**Comment by K-Guan** [comment]
Really? That can be version?

**Comment by FiveYellowMice** [comment]
Yes, that's why almost every AUR package end with '-git' has a weird
version number.

Kevin Guan <notifications@github.com>于2015年9月6日周日 下午10:40写道：

> Really? That can be version?
>

**Comment by K-Guan** [comment]
All right, that's it. Let me change my code.

**Comment by FiveYellowMice** [comment]
Pls tell me when you're done! (In this issue)

Kevin Guan <notifications@github.com>于2015年9月6日周日 下午10:42写道：

> All right, that's it. Let me change my code.
>

**Comment by K-Guan** [comment]
**Finished.** I make a .install file to display these text. Here is the `de-menu.install`: 
```
post_install(){
cat << EOF


The script will NOT detect what DE or WM you have installed,
you have to customize it yourself depend on your actual situation.

You have to edit it when you installed a new DE or WM in order to let it be in the menu.
EOF
}
```

And this is the `PKGBUILD`:
```
_gitname='de-menu'
pkgname='de-menu-git'
pkgver='a4e8908ffe'
pkgrel=1
pkgdesc="A desktop selection menu for startx users to avoid editing .xinitrc while switching desktops."
arch=('i686' 'x86_64')
url="https://github.com/FiveYellowMice/de-menu"
license=('GPL2')
makedepends='git'
install='de-menu.install'
depends=('xorg-xinit' 'xorg-server' 'bash')
source=("${_gitname}::git://github.com/FiveYellowMice/${_gitname}.git")
md5sums=('SKIP')

package() {
    cd "${srcdir}"/${_gitname}

    mkdir -p ${pkgdir}/usr/bin
    cp de-menu ${pkgdir}/usr/bin
}
```

**Comment by FiveYellowMice** [comment]
That's awesome!
